### ISSUE TITLE
Move package into Atom organization

### ISSUE THREAD

**Issue by as-cii** [atom/cached-run-in-this-context#1]
/cc: @maxbrunsfeld @nathansobo

**Comment by maxbrunsfeld** [comment]
@as-cii I believe I can do this if you add me as a collaborator on the repo whenever you get a chance.

**Comment by as-cii** [comment]
Done! 👍

**Comment by maxbrunsfeld** [comment]
Ok, I actually can't do it still, sorry. I think you actually have to 'transfer ownership' to me, and then I can transfer ownership to the atom org.

**Comment by as-cii** [comment]
> Ok, I actually can't do it still, sorry. I think you actually have to 'transfer ownership' to me, and then I can transfer ownership to the atom org.

Okay, I've just requested a transfer to your account. I guess I could have requested a direct ownership transfer to the Atom organization, but I am not 100% sure so I went ahead and gave ownership to your account. :+1:

**Comment by maxbrunsfeld** [comment]
Yeah, you're right; I didn't even know about that feature. Anyway I think everything's all set. Thanks!

**Comment by as-cii** [comment]
👏🎉🎉🎉
